//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheList.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblList
    {
        public int listID { get; set; }
        public Nullable<int> listTipoID { get; set; }
        public string listTitulo { get; set; }
        public string listDescricao { get; set; }
        public Nullable<int> listPrioridade { get; set; }
        public Nullable<int> listStatus { get; set; }
        public Nullable<System.DateTime> listLimitePrevisto { get; set; }
    
        public virtual tblListTipo tblListTipo { get; set; }
    }
}
